// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnwO3IplFkk6jI4fcA8b55eV2J4epq2e4',
    appId: '1:311312203906:web:ea58c021de6795ac93f49b',
    messagingSenderId: '311312203906',
    projectId: 'bookstore-cf8a5',
    authDomain: 'bookstore-cf8a5.firebaseapp.com',
    storageBucket: 'bookstore-cf8a5.appspot.com',
    measurementId: 'G-BJBL1XGKPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm1toNh5jETcjBIz2NVEsCoSFGwc5U_hk',
    appId: '1:311312203906:android:af6d114d321e5df493f49b',
    messagingSenderId: '311312203906',
    projectId: 'bookstore-cf8a5',
    storageBucket: 'bookstore-cf8a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAraKV3ivSDJ8Wzjm5NexBOdLrwQwglyPo',
    appId: '1:311312203906:ios:89b0318146bdc9a393f49b',
    messagingSenderId: '311312203906',
    projectId: 'bookstore-cf8a5',
    storageBucket: 'bookstore-cf8a5.appspot.com',
    iosBundleId: 'com.example.bookmngt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAraKV3ivSDJ8Wzjm5NexBOdLrwQwglyPo',
    appId: '1:311312203906:ios:89b0318146bdc9a393f49b',
    messagingSenderId: '311312203906',
    projectId: 'bookstore-cf8a5',
    storageBucket: 'bookstore-cf8a5.appspot.com',
    iosBundleId: 'com.example.bookmngt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnwO3IplFkk6jI4fcA8b55eV2J4epq2e4',
    appId: '1:311312203906:web:67a3cb5988e438a693f49b',
    messagingSenderId: '311312203906',
    projectId: 'bookstore-cf8a5',
    authDomain: 'bookstore-cf8a5.firebaseapp.com',
    storageBucket: 'bookstore-cf8a5.appspot.com',
    measurementId: 'G-7MPVM332XB',
  );
}
